server:
  port:
    8080

spring:
  application:
    name: api-gateway-v2
  main:
    web-application-type: reactive

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
#        health-check-path: "/actuator/health"

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: to-print-service
          uri: lb://print-service
          predicates:
            - Path=/print
            - Method=GET

        - id: to-texte-service
          uri: lb://texte-service
          predicates:
            - Path=/texte
            - Method=GET

        - id: mot
          uri: lb://print-service
          predicates:
            - Path=/mot
            - Method=GET
          filters:
            - name: AddRequestParameter
              args:
                name: mot
                value: gateway



management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics