server:
  port:
    8083

spring:
  application:
    name: print-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
#        health-check-path: "/actuator/health"

feign:
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
  client:
    config:
      user-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
      client-service:
        #error-decoder: bstorm.akimts.film.config.CustomErrorDecoder
        #retryer: bstorm.akimts.film.config.CustomRetryer
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics